name: CI Pipeline

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/iron'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Lint Code
        run: npm run lint

      - name: Create .env file
        run: |
          echo "POSTGRES_USER=local_user" >> .env
          echo "POSTGRES_PASSWORD=local_password" >> .env
          echo "POSTGRES_HOST=localhost" >> .env
          echo "POSTGRES_PORT=5432" >> .env
          echo "POSTGRES_DB=local_db" >> .env
          echo "DATABASE_URL=postgres://local_user:local_password@localhost:5432/local_db" >> .env

      - name: Build Docker Image and Run Container
        run: docker compose --profile prod up -d --build

      - name: Check Container Logs
        run: docker compose logs

      - name: Wait for Application to be Ready
        run: sleep 60

      - name: Run Tests
        run: npm run test

      - name: Stop Services
        if: always()
        run: docker compose down
