name: CI Pipeline

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: local_user
          POSTGRES_PASSWORD: local_password
          POSTGRES_DB: local_db

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/iron'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Lint Code
        run: npm run lint

      - name: Build Docker Image and Run Container
        run: docker compose --profile prod up -d --build

      - name: Wait for Application to be Ready
        run: sleep 30

      - name: Run Tests
        run: npm run test

      - name: Stop Services
        if: always()
        run: docker compose down
